In [1]:
import numpy as np

In [1]:
from sklearn import datasets

In [2]:
myirisdata=datasets.load_iris()

In [3]:
X_input=myirisdata.data

In [4]:
Y_target=myirisdata.target

In [5]:
X_input.shape

(150, 4)

In [6]:
Y_target.shape

(150,)

In [7]:
X_input_train=X_input[:-10]

In [8]:
X_input_train.shape

(140, 4)

In [9]:


X_input_test=X_input[-10:]

In [10]:


X_input_test.shape

(10, 4)

In [26]:
Y_target_train=Y_target[:-10]

In [28]:
Y_target_test=Y_target[-10:]

In [29]:
Y_target_test.shape

(10,)

In [30]:
Y_target_train.shape

(140,)

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
myknn=KNeighborsClassifier()

In [33]:
mymodel=myknn.fit(X_input_train,Y_target_train)

In [35]:
YA=Y_target_test

In [36]:
YA

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [37]:
YP=mymodel.predict(X_input_test)

In [39]:
YP

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [40]:
YA-YP

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
from sklearn import metrics

In [43]:
m=metrics.accuracy_score(YA,YP)

In [44]:
n=m*100

In [45]:
n

100.0